export default {
    "home": {
        text: "Home",
        exact: true,
        to: { name: "home" },
        parent: null,
    },
    "dashboard": {
        text: "Dashboard",
        exact: true,
        to: { name: "dashboard" },
        parent: 'home',
    },
    "profile": {
        text: "Perfil",
        exact: true,
        to: { name: "profile" },
        parent: 'home',
    },
    "employees.list": {
        text: "Funcionários",
        exact: true,
        to: { name: "employees.list" },
        parent: 'home',
    },
    "employees.new": {
        text: "Novo Funcionário",
        exact: true,
        to: { name: "employees.new" },
        parent: 'employees.list',
    },
    "employees.show": {
        text: "Funcionário",
        exact: true,
        to: { name: "employees.show", params: {} },
        params: ['employee_id'],
        parent: 'employees.list',
    },
    "teachers.list": {
        text: "Professores",
        exact: true,
        to: { name: "teachers.list" },
        parent: 'home',
    },
    "teachers.new": {
        text: "Novo Professor",
        exact: true,
        to: { name: "teachers.new" },
        parent: 'teachers.list',
    },
    "teachers.show": {
        text: "Professor",
        exact: true,
        to: { name: "teachers.show", params: {} },
        params: ['teacher_id'],
        parent: 'teachers.list',
    },
    "customers.list": {
        text: "Clientes",
        exact: true,
        to: { name: "customers.list" },
        parent: 'home',
    },
    "customers.new": {
        text: "Novo Cliente",
        exact: true,
        to: { name: "customers.new" },
        parent: 'customers.list',
    },
    "customers.show": {
        text: "Cliente",
        exact: true,
        to: { name: "customers.show", params: {} },
        params: ['customer_id'],
        parent: 'customers.list',
    },
    "billers.new": {
        text: "Novo Biller",
        exact: true,
        to: { name: "billers.new", params: {} },
        params: ['customer_id'],
        parent: 'customers.show',
    },
    "billers.show": {
        text: "Biller",
        exact: true,
        to: { name: "billers.show", params: {} },
        params: ['customer_id', 'biller_id'],
        parent: 'customers.show',
    },
    "students.list": {
        text: "Alunos",
        exact: true,
        to: { name: "students.list" },
        parent: 'home',
    },
    "students.new": {
        text: "Novo Aluno",
        exact: true,
        to: { name: "students.new", params: {} },
        params: ['customer_id'],
        parent: 'customers.show',
    },
    "students.show": {
        text: "Aluno",
        exact: true,
        to: { name: "students.show", params: {} },
        params: ['student_id'],
        parent: 'students.list',
    },
    "bugs.list": {
        text: "Bugs",
        exact: true,
        to: { name: "bugs.list" },
        parent: 'home',
    },
};
